name: TwitchAnnounce
main: dev.pilati.twitchannounce.spigot.TwitchAnnounce
version: 1.2
api-version: 1.16
permissions:
   twitchannounce.remove:
      default: op
   twitchannounce.add:
      default: op
   twitchannounce.list:
      default: op
   twitchannounce.announce:
      default: op
   twitchannounce.update:
      default: op
commands:
   twitchannounce:
      description: twitchannounce commands