name: TwitchAnnounce
main: dev.pilati.twitchannounce.bungee.TwitchAnnounce
version: 1.0
api-version: 1.16
permissions:
   twitchannounce.remove:
      default: op
   twitchannounce.add:
      default: op
   twitchannounce.list:
      default: op
   twitchannounce.announce:
      default: op
commands:
   twitchannounce:
      description: twitchannounce commands